# 1. Database - Use a clean name
internalDatabase:
  enabled: false
postgresql:
  enabled: true
  auth:
    database: nctracex
    username: ncusr
    password: 'DSF29jha64'
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 10Gi

# 2. Storage - Point to your MinIO
nextcloud:
  host: nc.tracexit.com
  # This makes MinIO your PRIMARY storage (no local HDD used for files)
  objectStore:
    enabled: true
    config:
      region: 'us-east-1'
      bucket: 'nextcloud'
      endpoint: 'minio.tracexit.com' # Change to your MinIO URL
      port: 443
      use_ssl: true
      autocreate: true
      key: 'rfibb9ivKUwQA7AxwPVD'
      secret: 'p98m97807cch4KhuhjefjJjQhy4w8wV26OWs2v8E'

  # 3. Keycloak Integration
  extraApps:
    oidc_login: https://github.com/pulsejet/nextcloud-oidc-login/releases/latest/download/oidc_login.tar.gz

  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array('192.168.20.110'),
        'overwriteprotocol' => 'https',
      );
    oidc.config.php: |-
      <?php
      $CONFIG = array (
        'oidc_login_client_id' => 'nextcloud',
        'oidc_login_client_secret' => 'E4KdTMA0caH3UtAeILi5RMVm9gRz0hom',
        'oidc_login_provider_url' => 'https://sso-kc.tracexit.com/realms/NC',
        'oidc_login_auto_redirect' => false, # Keep false until we verify login works
        'oidc_login_button_text' => 'Log in with Keycloak',
        'oidc_login_display_name_claim' => 'preferred_username',
        'oidc_login_use_id_token' => true,
      );

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: nc.tracexit.com
      pathType: Prefix