# 1. Database - Top Level
postgresql:
  enabled: true
  auth:
    database: nctracex
    username: ncusr
    password: 'DSF29jha64'
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 10Gi

# 2. Storage - Top Level (Standard for most Nextcloud charts)
objectStore:
  enabled: true
  config:
    region: 'us-east-1'
    bucket: 'nextcloud'
    endpoint: 'minio.minio.svc.cluster.local'
    port: 9000
    use_ssl: false # Set to false for internal cluster communication
    autocreate: true
    key: 'rfibb9ivKUwQA7AxwPVD'
    secret: 'p98m97807cch4KhuhjefjJjQhy4w8wV26OWs2v8E'

# 3. Nextcloud App Settings
nextcloud:
  host: nc.tracexit.com
  extraApps:
    oidc_login: https://github.com/pulsejet/nextcloud-oidc-login/releases/latest/download/oidc_login.tar.gz

  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array('192.168.20.110'),
        'overwriteprotocol' => 'https',
      );
    oidc.config.php: |-
      <?php
      $CONFIG = array (
        'oidc_login_client_id' => 'nextcloud',
        'oidc_login_client_secret' => 'E4KdTMA0caH3UtAeILi5RMVm9gRz0hom',
        'oidc_login_provider_url' => 'https://sso-kc.tracexit.com/realms/NC',
        'oidc_login_auto_redirect' => false,
        'oidc_login_button_text' => 'Log in with Keycloak',
        'oidc_login_display_name_claim' => 'preferred_username',
        'oidc_login_use_id_token' => true,
      );

# 4. Ingress - Top Level
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: nc.tracexit.com
      paths:
        - path: /
          pathType: Prefix