nextcloud:
  host: nextcloud.tracexit.com

persistence:
  enabled: true
  size: 20Gi

postgresql:
  enabled: true
  auth:
    username: ncusr
    password: dsf11jha64
    database: ncdb
    postgresPassword: DSF11jha%_64

service:
  type: ClusterIP